# Generated by Django 4.2 on 2023-04-12 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='carga_horario',
            new_name='carga_horaria',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='name',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='evento',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
